services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
        - backend
  bot:
    build: ./rocket-chat-bot
    restart: unless-stopped
    entrypoint: python3 app.py
    volumes:
      - ./rocket-chat-bot/app:/app:ro
    env_file:
      - ./rocket-chat-bot/.env
volumes:
  db_data:
